// lib/sample-data.ts
import type { Field } from "./types";

export const SAMPLE_FIELDS: Field[] = [
	{
		id: "patient_name",
		label: "Patient Name",
		value: "Margaret O. Chen",
		confidence: 0.99,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "dob",
		label: "Date of Birth",
		value: "03/14/1962",
		confidence: 0.98,
		tier: "high",
		source: "Layout",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "member_id",
		label: "Member ID",
		value: "BCBS-7745-2298",
		confidence: 0.97,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "group_number",
		label: "Group Number",
		value: "GRP-44219",
		confidence: 0.96,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "service_date",
		label: "Service Date",
		value: "06/02/2026",
		confidence: 0.95,
		tier: "high",
		source: "Layout",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "place_of_service",
		label: "Place of Service",
		value: "Outpatient Hospital",
		confidence: 0.93,
		tier: "high",
		source: "VLM",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "urgency",
		label: "Urgency",
		value: "Routine",
		confidence: 0.94,
		tier: "high",
		source: "Checkbox",
		type: "checkbox",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "icd10",
		label: "Primary Diagnosis (ICD-10)",
		value: "E11.65",
		confidence: 0.82,
		tier: "mid",
		source: "VLM",
		flag: "Code matched from handwritten notation. Confirm: E11.65 = Type 2 diabetes with hypoglycemia.",
		type: "text",
		needsReview: true,
		reviewed: false,
	},
	{
		id: "provider",
		label: "Provider · NPI",
		value: "Patel, R. · 1487338921",
		confidence: 0.64,
		tier: "low",
		source: "OCR",
		flag: "NPI partially obscured by signature stamp. Verify against provider directory before submit.",
		type: "text",
		needsReview: true,
		reviewed: false,
	},
];
