// lib/sample-data.ts
import type { Field } from "./types";

export const SAMPLE_FIELDS: Field[] = [
	{
		id: "patient_name",
		label: "Patient Name",
		value: "Jordan A. Whitmore",
		confidence: 0.99,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "dob",
		label: "Date of Birth",
		value: "11/03/1988",
		confidence: 0.98,
		tier: "high",
		source: "Layout",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "mrn",
		label: "MRN",
		value: "MRN-440921",
		confidence: 0.97,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "provider",
		label: "Ordering Provider",
		value: "Dr. Elena Vasquez",
		confidence: 0.96,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "npi",
		label: "NPI",
		value: "1629384750",
		confidence: 0.95,
		tier: "high",
		source: "Layout",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "site",
		label: "Site",
		value: "Riverside Clinic",
		confidence: 0.94,
		tier: "high",
		source: "OCR",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "collection_datetime",
		label: "Collection Date / Time",
		value: "05/21/2026  08:15 AM",
		confidence: 0.93,
		tier: "high",
		source: "Layout",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "fasting",
		label: "Fasting",
		value: "Yes",
		confidence: 0.92,
		tier: "high",
		source: "Checkbox",
		type: "checkbox",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "clinical_notes",
		label: "Clinical Indication",
		value: "Annual wellness visit. Monitor glycemic control and lipid profile.",
		confidence: 0.88,
		tier: "mid",
		source: "VLM",
		type: "text",
		needsReview: false,
		reviewed: true,
	},
	{
		id: "icd10",
		label: "ICD-10",
		value: "Z00.00, E11.9",
		confidence: 0.82,
		tier: "mid",
		source: "VLM",
		flag: "Confirm diagnosis codes match clinical indication.",
		type: "text",
		needsReview: true,
		reviewed: false,
	},
	{
		id: "urgency",
		label: "Priority",
		value: "Routine",
		confidence: 0.91,
		tier: "high",
		source: "Checkbox",
		type: "checkbox",
		needsReview: false,
		reviewed: true,
	},
];
